from pathlib import Path

root = Path('.')
tsx = root / 'app/rpg/RPGMode.tsx'
css = root / 'app/rpg/RPGMode.module.css'
progress = root / 'PROGRESS.md'

text = tsx.read_text()
text = text.replace('type AreaTransitionState = { phase: "depart" | "arrive"; targetName: string; targetKind: string; label: string } | null;\n', 'type AreaTransitionState = { phase: "depart" | "arrive"; targetName: string; targetKind: string; label: string } | null;\ntype DiscoveryState = { kind: "gold" | "item" | "equipment"; kicker: string; name: string; detail: string } | null;\n', 1)
text = text.replace('''function resultLineKind(line: string) {\n  if (line.includes("LEVEL UP")) return "level";\n  if (line.startsWith("EXP +")) return "reward";\n  if (/手に入れた|覚えた|習得|取得/.test(line)) return "acquire";\n  if (/失った|YOU AWAKEN/.test(line)) return "loss";\n  return "story";\n}\n''', '''function resultLineKind(line: string) {\n  if (line.includes("LEVEL UP")) return "level";\n  if (line.startsWith("EXP +")) return "reward";\n  if (/手に入れた|覚えた|習得|取得/.test(line)) return "acquire";\n  if (/失った|YOU AWAKEN/.test(line)) return "loss";\n  return "story";\n}\nfunction resultAcquireKind(line: string) {\n  if (line.startsWith("技「")) return "technique";\n  if (Object.values(EQUIPMENT).some((equipment) => line.startsWith(equipment.name))) return "equipment";\n  return "item";\n}\n''', 1)
text = text.replace('''  const [fieldReturn, setFieldReturn] = useState(false);\n  const [areaTransition, setAreaTransition] = useState<AreaTransitionState>(null);\n  const [walkFrame, setWalkFrame] = useState(0);\n''', '''  const [fieldReturn, setFieldReturn] = useState(false);\n  const [areaTransition, setAreaTransition] = useState<AreaTransitionState>(null);\n  const [discovery, setDiscovery] = useState<DiscoveryState>(null);\n  const [walkFrame, setWalkFrame] = useState(0);\n''', 1)
text = text.replace('if (screen !== "overworld" || service || battle || result || areaTransition) return;', 'if (screen !== "overworld" || service || battle || result || areaTransition || discovery) return;', 1)
text = text.replace('''  function interact() {\n    if (areaTransition) return;\n''', '''  function interact() {\n    if (discovery) { setDiscovery(null); playSfx("uiSelect"); return; }\n    if (areaTransition) return;\n''', 1)
old_chest = '''    if (chest) {\n      let text = "宝箱を開けた。";\n      commit((current) => {\n        let next = { ...current, openedChests: addUnique(current.openedChests, chest.id) };\n        if (chest.gold) { next = { ...next, gold: next.gold + chest.gold }; text = `${chest.gold} GOLDを見つけた。`; }\n        if (chest.item) { next = giveItem(next, chest.item); text = `${ITEMS[chest.item].name}を見つけた。`; }\n        if (chest.equipment) { next = { ...next, equipmentOwned: addUnique(next.equipmentOwned, chest.equipment) }; text = `${EQUIPMENT[chest.equipment].name}を見つけた。`; }\n        saveGame(next); return next;\n      });\n      openDialogue("TREASURE", [text]); playSfx("treasure"); return;\n    }\n'''
new_chest = '''    if (chest) {\n      let found: Exclude<DiscoveryState, null> = { kind: "item", kicker: "TREASURE FOUND", name: "TREASURE", detail: "宝箱を開けた。" };\n      if (chest.gold) found = { kind: "gold", kicker: "TREASURE FOUND", name: `${chest.gold} GOLD`, detail: "旅の資金を手に入れた。" };\n      if (chest.item) found = { kind: "item", kicker: "ITEM ACQUIRED", name: ITEMS[chest.item].name, detail: "ITEMを手に入れた。" };\n      if (chest.equipment) found = { kind: "equipment", kicker: "EQUIPMENT ACQUIRED", name: EQUIPMENT[chest.equipment].name, detail: "EQUIPMENTを手に入れた。" };\n      commit((current) => {\n        let next = { ...current, openedChests: addUnique(current.openedChests, chest.id) };\n        if (chest.gold) next = { ...next, gold: next.gold + chest.gold };\n        if (chest.item) next = giveItem(next, chest.item);\n        if (chest.equipment) next = { ...next, equipmentOwned: addUnique(next.equipmentOwned, chest.equipment) };\n        saveGame(next); return next;\n      });\n      setDiscovery(found); playSfx("treasure"); return;\n    }\n'''
if old_chest not in text:
    raise SystemExit('chest block not found')
text = text.replace(old_chest, new_chest, 1)
text = text.replace('function openMenu() { if (screen === "overworld" && !areaTransition) {', 'function openMenu() { if (screen === "overworld" && !areaTransition && !discovery) {', 1)
marker = '''      {areaTransition ? <div className={styles.areaTransition} data-phase={areaTransition.phase} data-kind={areaTransition.targetKind} role="status" aria-live="polite">\n        <span>{areaTransition.phase === "depart" ? "TRAVEL" : "AREA"}</span><strong>{areaTransition.targetName}</strong><small>{areaTransition.label}</small>\n      </div> : null}\n'''
insert = marker + '''      {discovery ? <div className={styles.discoveryOverlay} data-kind={discovery.kind} onPointerDown={(event) => { event.preventDefault(); setDiscovery(null); playSfx("uiSelect"); }}>\n        <div className={styles.discoveryCard} data-kind={discovery.kind}>\n          <span>{discovery.kicker}</span><i aria-hidden="true">{discovery.kind === "gold" ? "G" : discovery.kind === "equipment" ? "E" : "I"}</i><strong>{discovery.name}</strong><p>{discovery.detail}</p><small>A / TAP • CONTINUE</small>\n        </div>\n      </div> : null}\n'''
if marker not in text:
    raise SystemExit('area transition render marker not found')
text = text.replace(marker, insert, 1)
old_result = '''<div className={styles.resultLines}>{result.lines.map((line, index) => <p data-kind={resultLineKind(line)} style={{ "--result-index": index } as Record<string, number>} key={`${index}-${line}`}>{line}</p>)}</div>'''
new_result = '''<div className={styles.resultLines}>{result.lines.map((line, index) => <p data-kind={resultLineKind(line)} data-acquire={resultLineKind(line) === "acquire" ? resultAcquireKind(line) : undefined} style={{ "--result-index": index } as Record<string, number>} key={`${index}-${line}`}>{line}</p>)}</div>'''
if old_result not in text:
    raise SystemExit('result lines render not found')
text = text.replace(old_result, new_result, 1)
tsx.write_text(text)

addition = r'''

/* SFC visual reconstruction pass 26 — discovery and acquisition */
.discoveryOverlay{position:fixed;z-index:195;inset:0;display:grid;place-items:center;padding:max(14px,env(safe-area-inset-top)) 14px max(14px,env(safe-area-inset-bottom));background:radial-gradient(circle at 50% 45%,rgba(255,226,112,.1),rgba(2,2,6,.76) 58%,rgba(2,2,5,.9));touch-action:none}
.discoveryOverlay::before{content:"";position:absolute;inset:0;pointer-events:none;opacity:.16;background:repeating-linear-gradient(0deg,transparent 0 3px,rgba(255,255,255,.12) 4px)}
.discoveryCard{--discovery:#ffe273;position:relative;width:min(88vw,356px);min-height:205px;display:grid;grid-template-columns:66px 1fr;grid-template-rows:auto auto auto 1fr auto;gap:4px 12px;align-items:center;padding:17px 17px 13px;border:3px solid #f1ead5;background:linear-gradient(180deg,#16131c,#08080d 72%);box-shadow:0 0 0 2px #030305,0 0 0 5px #6e5830,7px 8px #000;animation:discoveryIn 340ms steps(6,end) both}
.discoveryCard[data-kind="item"]{--discovery:#7fe4ef}.discoveryCard[data-kind="equipment"]{--discovery:#c7a5ff}
.discoveryCard::before{content:"";position:absolute;left:14px;right:14px;top:11px;height:2px;background:linear-gradient(90deg,transparent,var(--discovery) 20% 80%,transparent);opacity:.72}.discoveryCard::after{content:"";position:absolute;left:50%;top:73px;width:124px;height:44px;transform:translate(-50%,-50%);z-index:-1;background:repeating-conic-gradient(from 0deg,rgba(255,255,255,.13) 0 7deg,transparent 7deg 17deg);clip-path:polygon(50% 0,58% 36%,86% 14%,66% 43%,100% 50%,66% 57%,86% 86%,58% 64%,50% 100%,42% 64%,14% 86%,34% 57%,0 50%,34% 43%,14% 14%,42% 36%);animation:discoveryBurst 700ms steps(8,end) both}
.discoveryCard>span{grid-column:1/-1;justify-self:center;padding:3px 8px;border-block:1px solid #6b6251;color:var(--discovery);font:900 7px/1 monospace;letter-spacing:.16em}.discoveryCard>i{grid-column:1;grid-row:2/5;justify-self:center;width:52px;height:52px;display:grid;place-items:center;border:3px solid var(--discovery);background:#0a0a10;color:var(--discovery);box-shadow:0 0 0 2px #020204,4px 5px #000;font:1000 24px/1 monospace;font-style:normal;text-shadow:2px 2px #000}.discoveryCard>strong{grid-column:2;align-self:end;color:#fff4d4;font-size:17px;line-height:1.15;text-shadow:2px 2px #000;overflow-wrap:anywhere}.discoveryCard>p{grid-column:2;margin:0;color:#c8c2b8;font-size:9px;line-height:1.45}.discoveryCard>small{grid-column:1/-1;justify-self:end;margin-top:6px;color:#8f8a91;font-size:6px;letter-spacing:.08em;animation:storyPrompt 720ms steps(2,end) infinite}
.resultLines p[data-kind="acquire"]{position:relative;padding-left:67px!important;text-align:left!important}.resultLines p[data-kind="acquire"]::before{position:absolute;left:6px;top:50%;transform:translateY(-50%);min-width:52px;padding:3px 4px;border:1px solid var(--accent2);background:#08090e;color:var(--accent);font:900 5px/1 monospace;letter-spacing:.08em;text-align:center}.resultLines p[data-acquire="item"]::before{content:"ITEM"}.resultLines p[data-acquire="equipment"]::before{content:"EQUIPMENT";color:#c9adff;border-color:#705a8d}.resultLines p[data-acquire="technique"]::before{content:"TECHNIQUE";color:#7de6ef;border-color:#386c75}.resultLines p[data-acquire="technique"]{border-left-color:#65dbe6!important;background:linear-gradient(90deg,rgba(44,105,117,.22),rgba(8,9,14,.86))!important}.resultLines p[data-acquire="equipment"]{border-left-color:#a485d1!important;background:linear-gradient(90deg,rgba(90,62,117,.22),rgba(8,9,14,.86))!important}
@keyframes discoveryIn{0%{opacity:0;transform:scaleY(.18);filter:brightness(2)}30%{opacity:1;transform:scaleY(.82)}58%{transform:scaleY(1.05)}100%{opacity:1;transform:scaleY(1);filter:none}}@keyframes discoveryBurst{0%{opacity:0;transform:translate(-50%,-50%) scale(.3)}42%{opacity:1}100%{opacity:0;transform:translate(-50%,-50%) scale(1.3)}}
@media(max-height:620px){.discoveryCard{min-height:162px;grid-template-columns:54px 1fr;padding:12px 14px 9px}.discoveryCard>i{width:44px;height:44px;font-size:20px}.discoveryCard>strong{font-size:14px}.discoveryCard>p{font-size:8px}.discoveryCard::after{top:59px}}
@media(prefers-reduced-motion:reduce){.discoveryCard,.discoveryCard::after,.discoveryCard>small{animation:none!important}}
'''
css.write_text(css.read_text() + addition)

section = '''\n\n## SFC Visual Reconstruction Pass 26 — Discovery and acquisition presentation\n- Replaced generic TREASURE dialogue for field chests with a dedicated discovery ceremony that distinguishes GOLD, ITEM and EQUIPMENT rewards while preserving the same tap-to-continue cadence.\n- Added discovery input locking so movement/menu actions cannot fire underneath the acquisition card; the next A/TAP dismisses it and immediately returns control to exploration.\n- Split battle-result acquisition rows into ITEM, EQUIPMENT and TECHNIQUE materials so training rewards and boss technique unlocks no longer read as identical text rows.\n- Chest contents, inventory limits, equipment ownership, reward formulas, technique grants, save data, encounter logic and Chapter Battle remain unchanged.\n'''
progress.write_text(progress.read_text() + section)
