from pathlib import Path

css_path = Path("app/rpg/RPGMode.module.css")
progress_path = Path("PROGRESS.md")
css = css_path.read_text()
marker = "/* SFC visual reconstruction pass 22 — field menu reconstruction */"
if marker in css:
    raise SystemExit("pass 22 already present")

css += r'''

/* SFC visual reconstruction pass 22 — field menu reconstruction */
.menuOverlay{place-items:center;background:rgba(2,2,6,.82);padding:max(10px,env(safe-area-inset-top)) 10px max(10px,env(safe-area-inset-bottom));backdrop-filter:blur(1px)}
.menuOverlay::before{content:"";position:absolute;inset:0;pointer-events:none;opacity:.14;background:repeating-linear-gradient(0deg,transparent 0 3px,rgba(255,255,255,.1) 4px),radial-gradient(circle at 50% 42%,color-mix(in srgb,var(--accent2) 22%,transparent),transparent 54%)}
.menuWindow{position:relative;width:min(95vw,420px);max-height:84dvh;display:grid;grid-template-rows:auto auto minmax(0,1fr) auto;gap:0;padding:0;border:0;background:transparent;box-shadow:0 0 0 2px #030305,7px 8px 0 rgba(0,0,0,.68)}
.menuWindow>header{min-height:38px;display:flex;align-items:center;justify-content:space-between;padding:5px 7px 5px 10px;border:3px solid #f2ead2;border-bottom-width:2px;background:linear-gradient(180deg,color-mix(in srgb,var(--panel) 84%,#252131),var(--panel2));box-shadow:inset 0 0 0 2px #07070c,inset 0 -2px color-mix(in srgb,var(--accent2) 58%,#111)}
.menuWindow>header strong{display:flex;align-items:center;gap:7px;color:#fff5d8;font-size:11px;letter-spacing:.08em;text-shadow:2px 2px #000}.menuWindow>header strong::before{content:"PRISM";padding:3px 5px;border:1px solid var(--accent2);background:#07080d;color:var(--accent);font-size:6px;letter-spacing:.16em;box-shadow:2px 2px #000}
.menuWindow button{border-radius:0;font-family:inherit}.menuWindow>header button{min-width:82px;min-height:27px;border:2px solid #928d82;background:#171821;color:#d8d5ca;font:900 7px/1 monospace;box-shadow:inset 0 0 0 1px #050507}.menuWindow>header button:active{transform:translateY(1px);background:var(--accent2);color:#fff}
.menuTabs{position:relative;display:grid;grid-template-columns:repeat(3,1fr);gap:2px;padding:5px;border-left:3px solid #f2ead2;border-right:3px solid #f2ead2;background:#07080d;box-shadow:inset 0 0 0 2px #11131c}
.menuTabs::after{content:"COMMAND";position:absolute;right:7px;top:-7px;padding:1px 4px;background:#07080d;color:color-mix(in srgb,var(--accent) 75%,#aaa);font:900 5px/1 monospace;letter-spacing:.14em}
.menuTabs button{position:relative;min-height:39px;padding:5px 5px 5px 29px;border:2px solid #464a56;background:linear-gradient(180deg,#151722,#0b0c12);color:#b8b9c1;font:900 7px/1.1 monospace;text-align:left;letter-spacing:.05em;box-shadow:inset 0 0 0 1px #050507}.menuTabs button::before{position:absolute;left:8px;top:50%;transform:translateY(-50%);width:13px;height:13px;display:grid;place-items:center;border:1px solid #4e5260;background:#090a10;color:#7b7f8b;font-size:7px;box-shadow:1px 1px #000}.menuTabs button:nth-child(1)::before{content:"◆"}.menuTabs button:nth-child(2)::before{content:"▣"}.menuTabs button:nth-child(3)::before{content:"◇"}.menuTabs button:nth-child(4)::before{content:"✦"}.menuTabs button:nth-child(5)::before{content:"▤"}.menuTabs button:nth-child(6)::before{content:"■"}.menuTabs button[data-active="true"]{z-index:1;border-color:#f3e8c7;background:linear-gradient(180deg,color-mix(in srgb,var(--accent2) 72%,#252130),#15131c);color:#fff7de;box-shadow:0 0 0 1px var(--accent),inset 3px 0 var(--accent),inset 0 0 0 1px #09080d;text-shadow:1px 1px #000}.menuTabs button[data-active="true"]::before{border-color:#fff2c5;background:var(--accent);color:#141018;box-shadow:0 0 0 1px #000}.menuTabs button:active{transform:translateY(1px)}
.menuContent,.shopList{min-height:170px;max-height:48dvh;overflow:auto;display:grid;align-content:start;gap:3px;padding:8px;border:3px solid #f2ead2;border-top-width:2px;border-bottom-width:2px;background:linear-gradient(180deg,#0d1019,#07080e 72%);box-shadow:inset 0 0 0 2px #040509,inset 0 0 0 3px color-mix(in srgb,var(--accent2) 24%,transparent);scrollbar-width:thin}
.menuContent h2{position:relative;margin:0 0 4px;padding:7px 8px 7px 13px;border:2px solid var(--accent2);background:linear-gradient(90deg,color-mix(in srgb,var(--accent2) 34%,#10111a),#0a0b11);color:#fff4d2;font-size:14px;letter-spacing:.04em;text-shadow:2px 2px #000}.menuContent h2::before{content:"";position:absolute;left:4px;top:5px;bottom:5px;width:3px;background:var(--accent)}
.menuContent p,.shopList p{margin:0;padding:5px 7px;border-left:2px solid #343743;background:#0b0d14;color:#c8c6bd;font-size:8px;line-height:1.35}.menuContent:has(>h2)>p{display:flex;align-items:center;min-height:28px;border-left-color:color-mix(in srgb,var(--accent2) 72%,#343743);background:linear-gradient(90deg,#0d1018,#08090f);font-weight:800}.menuContent:has(>h2)>p:nth-of-type(1){color:#b9f6cf}.menuContent:has(>h2)>p:nth-of-type(2){color:#d2d4e2}.menuContent:has(>h2)>p:nth-of-type(3){color:#dfc985}
.menuContent>button{min-height:36px;margin-top:4px;border:2px solid #737786;background:#12141f;color:#d9d7cf;font:900 8px/1 monospace;box-shadow:inset 0 0 0 1px #050507}.menuContent>button:active{background:var(--accent2);color:#fff}
.listRow,.shopList>button,.memoRow{position:relative;min-height:48px;display:grid!important;grid-template-columns:1fr auto;gap:2px 7px;align-items:center;padding:6px 8px 6px 12px;border:1px solid #373b46!important;border-left:3px solid #4f5360!important;background:linear-gradient(90deg,#10121a,#0a0b11)!important;text-align:left;box-shadow:none!important}.listRow::before,.shopList>button::before,.memoRow::before{content:"";position:absolute;left:4px;top:7px;bottom:7px;width:2px;background:#555966}.listRow b,.shopList b,.memoRow b{font-size:9px;color:#f0ecdd;text-shadow:1px 1px #000}.listRow span,.shopList span{color:var(--accent);font-size:7px;font-weight:900}.listRow small,.shopList small,.memoRow small{grid-column:1/-1;color:#9ea2ad;font-size:7px;line-height:1.3}.listRow:active,.shopList>button:active,.memoRow:active{transform:translateX(2px);background:color-mix(in srgb,var(--accent2) 28%,#0b0c12)!important}.listRow[data-equipped="true"]{border-color:#83dff1!important;border-left-color:#83dff1!important;background:linear-gradient(90deg,#12333d,#0a151a)!important}.listRow[data-equipped="true"]::before{background:#8cf0ff;box-shadow:0 0 4px rgba(130,235,255,.45)}.listRow[data-equipped="true"] span::before{content:"▶ ";color:#c9fbff}.memoRow[data-new="true"]{border-color:color-mix(in srgb,var(--accent) 55%,#414451)!important;border-left-color:var(--accent)!important}.memoRow[data-new="true"]::before{background:var(--accent)}.memoRow[data-new="true"] b::before{content:"NEW • ";color:var(--accent)}
.shopList>p{margin-bottom:3px;border:2px solid var(--accent2);background:#0b0d14;color:#eee0b8;font-weight:900}.shopList>button span{min-width:44px;padding:2px 4px;border:1px solid #645932;background:#151208;text-align:center;color:#f3d16e}.shopList>button::after{content:"BUY";position:absolute;right:7px;bottom:5px;color:#5e626d;font:900 5px/1 monospace;letter-spacing:.12em}
.servicePanel{display:grid;align-content:start;gap:5px;min-height:0;padding:8px;border:2px solid #4b4f5b;background:linear-gradient(180deg,#0d1019,#08090f);box-shadow:inset 0 0 0 1px #050507}.servicePanel strong{display:block;padding:6px 7px;border-bottom:2px solid var(--accent2);color:var(--accent);font-size:11px;letter-spacing:.08em}.servicePanel p{border-left:0;background:transparent;color:#aaaeb8}.servicePanel button{min-height:36px;border:2px solid #4d515e;background:#12141d;color:#e5e2d8;font:900 8px/1 monospace}.servicePanel button:active{border-color:var(--accent);background:var(--accent2)}
.menuWindow footer{min-height:28px;display:flex;align-items:center;padding:4px 8px;border:3px solid #f2ead2;border-top-width:2px;background:linear-gradient(180deg,#11131c,#08090e);color:#aaa9a2;font-size:7px;line-height:1.25;box-shadow:inset 0 0 0 2px #040509}.menuWindow footer::before{content:"INFO";margin-right:7px;padding:2px 4px;border:1px solid var(--accent2);color:var(--accent);font-size:5px;letter-spacing:.12em}
@media(max-height:700px){.menuWindow{max-height:91dvh}.menuWindow>header{min-height:34px}.menuTabs{padding:3px}.menuTabs button{min-height:33px;padding-top:3px;padding-bottom:3px}.menuContent,.shopList{min-height:135px;max-height:49dvh;padding:5px}.listRow,.shopList>button,.memoRow{min-height:42px;padding-top:4px;padding-bottom:4px}.menuWindow footer{min-height:24px}}
'''
css_path.write_text(css)

progress = progress_path.read_text()
progress += r'''

## SFC Visual Reconstruction Pass 22 — Field menu reconstruction
- Rebuilt FIELD MENU as a four-part SFC command screen: framed title bar, six command slots, dedicated content window and persistent INFO footer.
- STATUS now reads as a compact character sheet; ITEM / EQUIP / TECH / MEMO use denser role-specific rows instead of web-card styling, with equipped/new states receiving stronger pixel cues.
- SHOP and SAVE/service panels now share the same game-window grammar, including compact currency/action framing and stepped pressed states.
- Menu tab logic, inventory/equipment behavior, prices, save/import/export, touch targets and RPG progression remain unchanged.
'''
progress_path.write_text(progress)
