from pathlib import Path

root = Path('.')
tsx = root / 'app/rpg/RPGMode.tsx'
css = root / 'app/rpg/RPGMode.module.css'
progress = root / 'PROGRESS.md'
text = tsx.read_text()

repls = [
('''type DiscoveryState = { kind: "gold" | "item" | "equipment"; kicker: string; name: string; detail: string } | null;''', '''type DiscoveryState = { kind: "gold" | "item" | "equipment"; kicker: string; name: string; detail: string } | null;\ntype EncounterCueKind = "wild" | "danger" | "fixed" | "boss" | "trial";\ntype EncounterCueState = { enemyId: string; kind: EncounterCueKind; title: string; subtitle: string; context: Omit<BattleContext, "enemyId"> } | null;'''),
('''type InteractionMarkerKind = "talk" | "treasure" | "danger" | "exit";''', '''type InteractionMarkerKind = "talk" | "treasure" | "danger" | "boss" | "exit";'''),
('''  const accent = kind === "danger" ? "#ff6a66" : kind === "treasure" ? "#ffd765" : kind === "exit" ? "#7ee8ef" : "#f1d06a";''', '''  const accent = kind === "boss" ? "#ffe784" : kind === "danger" ? "#ff6a66" : kind === "treasure" ? "#ffd765" : kind === "exit" ? "#7ee8ef" : "#f1d06a";'''),
('''  } else if (kind === "danger") {\n    context.fillRect(x + 10, y - 20, 2, 4); context.fillRect(x + 10, y - 15, 2, 1);\n  } else {''', '''  } else if (kind === "danger" || kind === "boss") {\n    context.fillRect(x + 10, y - 20, 2, 4); context.fillRect(x + 10, y - 15, 2, 1);\n    if (kind === "boss") { context.fillRect(x + 8, y - 22, 1, 2); context.fillRect(x + 13, y - 22, 1, 2); }\n  } else {'''),
('''  const [areaTransition, setAreaTransition] = useState<AreaTransitionState>(null);\n  const [discovery, setDiscovery] = useState<DiscoveryState>(null);''', '''  const [areaTransition, setAreaTransition] = useState<AreaTransitionState>(null);\n  const [discovery, setDiscovery] = useState<DiscoveryState>(null);\n  const [encounterCue, setEncounterCue] = useState<EncounterCueState>(null);\n  const [dangerWarning, setDangerWarning] = useState<string | null>(null);'''),
('''  const transitionTimer = useRef<number | null>(null);\n  const arrivalTimer = useRef<number | null>(null);''', '''  const transitionTimer = useRef<number | null>(null);\n  const arrivalTimer = useRef<number | null>(null);\n  const encounterTimer = useRef<number | null>(null);\n  const dangerTimer = useRef<number | null>(null);'''),
('''    if (screen !== "overworld" || service || battle || result || areaTransition || discovery) return;''', '''    if (screen !== "overworld" || service || battle || result || areaTransition || discovery || encounterCue) return;'''),
('''    const code = tileAt(map, nextPosition.x, nextPosition.y);\n    const danger = isDangerTile(code);''', '''    const code = tileAt(map, nextPosition.x, nextPosition.y);\n    const danger = isDangerTile(code);\n    const enteringDanger = danger && !isDangerTile(tileAt(map, current.position.x, current.position.y));\n    if (enteringDanger) {\n      setDangerWarning(map.kind === "danger" ? map.name : "DANGER ZONE");\n      if (dangerTimer.current) window.clearTimeout(dangerTimer.current);\n      dangerTimer.current = window.setTimeout(() => setDangerWarning(null), 760);\n    }'''),
('''      window.setTimeout(() => startBattle(chooseEncounter(nextPosition, danger)), 120);''', '''      window.setTimeout(() => startBattle(chooseEncounter(nextPosition, danger), {}, danger ? "danger" : "wild"), 90);'''),
('''  function interact() {\n    if (discovery) { setDiscovery(null); playSfx("uiSelect"); return; }\n    if (areaTransition) return;''', '''  function interact() {\n    if (discovery) { setDiscovery(null); playSfx("uiSelect"); return; }\n    if (areaTransition || encounterCue) return;'''),
('''  function startBattle(enemyId: string, context: Omit<BattleContext, "enemyId"> = {}) {\n    if (!ENEMIES[enemyId]) return;\n    primeAudio(); playSfx("battleStart"); saveGame(save); setBattle({ enemyId, ...context }); setScreen("battle"); setResult(null);\n  }''', '''  function startBattle(enemyId: string, context: Omit<BattleContext, "enemyId"> = {}, requestedKind?: EncounterCueKind) {\n    const enemy = ENEMIES[enemyId];\n    if (!enemy || encounterCue) return;\n    const kind: EncounterCueKind = requestedKind ?? (context.training ? "trial" : enemy.boss ? "boss" : context.fixedId ? "fixed" : "wild");\n    const title = kind === "boss" ? "BOSS APPROACH" : kind === "trial" ? "TRIAL" : kind === "fixed" ? "GUARDIAN" : kind === "danger" ? "DANGER ENCOUNTER" : "ENCOUNTER";\n    const subtitle = kind === "boss" ? "A POWERFUL PRESENCE" : kind === "trial" ? "MASTER'S TEST" : kind === "fixed" ? "PATH BLOCKED" : kind === "danger" ? "HOSTILE TERRITORY" : "WILD FOE";\n    const delay = kind === "boss" ? 620 : kind === "trial" ? 460 : kind === "fixed" ? 420 : kind === "danger" ? 320 : 240;\n    primeAudio(); playSfx("battleStart"); saveGame(saveRef.current); setResult(null); setEncounterCue({ enemyId, kind, title, subtitle, context });\n    if (encounterTimer.current) window.clearTimeout(encounterTimer.current);\n    encounterTimer.current = window.setTimeout(() => {\n      setEncounterCue(null); setBattle({ enemyId, ...context }); setScreen("battle");\n    }, delay);\n  }'''),
('''  function openMenu() { if (screen === "overworld" && !areaTransition && !discovery) { primeAudio(); playSfx("uiSelect"); setService(null); setScreen("menu"); } }''', '''  function openMenu() { if (screen === "overworld" && !areaTransition && !discovery && !encounterCue) { primeAudio(); playSfx("uiSelect"); setService(null); setScreen("menu"); } }'''),
('''      const markerKind: InteractionMarkerKind = frontNpc ? "talk" : frontChest ? "treasure" : frontFixed ? "danger" : "exit";''', '''      const markerKind: InteractionMarkerKind = frontNpc ? "talk" : frontChest ? "treasure" : frontFixed ? (ENEMIES[frontFixed.enemyId]?.boss ? "boss" : "danger") : "exit";'''),
('''  useEffect(() => () => { stopHold(); if (transitionTimer.current) window.clearTimeout(transitionTimer.current); if (arrivalTimer.current) window.clearTimeout(arrivalTimer.current); stopRpgMusic(); setSfxEnabled(true); }, []);''', '''  useEffect(() => () => { stopHold(); if (transitionTimer.current) window.clearTimeout(transitionTimer.current); if (arrivalTimer.current) window.clearTimeout(arrivalTimer.current); if (encounterTimer.current) window.clearTimeout(encounterTimer.current); if (dangerTimer.current) window.clearTimeout(dangerTimer.current); stopRpgMusic(); setSfxEnabled(true); }, []);'''),
('''    <main className={styles.rpg} data-map={map.id} data-kind={map.kind} data-returning={fieldReturn ? "true" : "false"} data-area-phase={areaTransition?.phase ?? "none"}>\n      {areaTransition ? <div className={styles.areaTransition} data-phase={areaTransition.phase} data-kind={areaTransition.targetKind} role="status" aria-live="polite">\n        <span>{areaTransition.phase === "depart" ? "TRAVEL" : "AREA"}</span><strong>{areaTransition.targetName}</strong><small>{areaTransition.label}</small>\n      </div> : null}\n      {discovery ?''', '''    <main className={styles.rpg} data-map={map.id} data-kind={map.kind} data-returning={fieldReturn ? "true" : "false"} data-area-phase={areaTransition?.phase ?? "none"} data-encounter={encounterCue?.kind ?? "none"}>\n      {areaTransition ? <div className={styles.areaTransition} data-phase={areaTransition.phase} data-kind={areaTransition.targetKind} role="status" aria-live="polite">\n        <span>{areaTransition.phase === "depart" ? "TRAVEL" : "AREA"}</span><strong>{areaTransition.targetName}</strong><small>{areaTransition.label}</small>\n      </div> : null}\n      {dangerWarning && !encounterCue ? <div className={styles.dangerWarning} role="status" aria-live="polite"><span>WARNING</span><strong>{dangerWarning}</strong><small>ENCOUNTER RATE UP</small></div> : null}\n      {encounterCue ? <div className={styles.encounterCue} data-kind={encounterCue.kind} role="status" aria-live="assertive">\n        <span>{encounterCue.subtitle}</span><strong>{encounterCue.title}</strong><b>{ENEMIES[encounterCue.enemyId]?.name ?? encounterCue.enemyId}</b><i aria-hidden="true" />\n      </div> : null}\n      {discovery ?'''),
]
for old, new in repls:
    if old not in text:
        raise SystemExit(f'target not found:\n{old[:180]}')
    text = text.replace(old, new, 1)
tsx.write_text(text)

addition = r'''

/* SFC visual reconstruction pass 27 — encounter warnings and boss approach */
.dangerWarning{position:absolute;z-index:175;top:max(91px,calc(env(safe-area-inset-top) + 82px));left:50%;width:min(82%,330px);transform:translateX(-50%);display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:7px;padding:5px 8px;border:2px solid #ff726d;background:#18080d;box-shadow:0 0 0 2px #050507,3px 4px #000;color:#fff0dc;pointer-events:none;animation:dangerZoneIn 760ms steps(7,end) both}.dangerWarning span{padding:2px 4px;background:#c83a43;color:#fff;font:1000 6px/1 monospace;letter-spacing:.12em}.dangerWarning strong{font:1000 9px/1 monospace;letter-spacing:.08em;text-align:left}.dangerWarning small{color:#ff9d91;font:900 5px/1 monospace;letter-spacing:.08em;white-space:nowrap}
.encounterCue{position:fixed;z-index:235;inset:0;display:grid;place-items:center;align-content:center;gap:8px;overflow:hidden;background:rgba(2,2,5,.78);color:#fff6dc;text-align:center;pointer-events:auto;isolation:isolate;animation:encounterCueOut 240ms steps(4,end) reverse both}.encounterCue::before,.encounterCue::after{content:"";position:absolute;z-index:-1;left:0;right:0;height:42%;background:#050509}.encounterCue::before{top:0;animation:encounterShutterTop 260ms steps(5,end) both}.encounterCue::after{bottom:0;animation:encounterShutterBottom 260ms steps(5,end) both}.encounterCue>span{padding:3px 8px;border-block:1px solid #696270;color:#bbb4c2;font:900 6px/1 monospace;letter-spacing:.2em}.encounterCue>strong{position:relative;padding:8px 14px;border:2px solid #ded8c7;background:#0a0a10;box-shadow:0 0 0 2px #020204,4px 5px #000;color:#fff0c4;font:1000 clamp(18px,6vw,28px)/1 monospace;letter-spacing:.08em;text-shadow:2px 2px #000}.encounterCue>b{color:#d0c9bb;font:1000 10px/1 monospace;letter-spacing:.08em;text-transform:uppercase}.encounterCue>i{position:absolute;z-index:-1;left:50%;top:50%;width:180px;height:180px;transform:translate(-50%,-50%) rotate(45deg);border:2px solid rgba(255,255,255,.13);box-shadow:0 0 0 14px rgba(255,255,255,.025),0 0 0 28px rgba(255,255,255,.018)}
.encounterCue[data-kind="wild"]>strong{border-color:#d8cfb6}.encounterCue[data-kind="danger"]{background:rgba(18,2,7,.83)}.encounterCue[data-kind="danger"]>span{border-color:#7f2b37;color:#ff9a91}.encounterCue[data-kind="danger"]>strong{border-color:#ff6b67;color:#ffd7c8;background:#21070d;animation:dangerEncounterPulse 160ms steps(2,end) 2}.encounterCue[data-kind="fixed"]{background:rgba(6,7,12,.86)}.encounterCue[data-kind="fixed"]>strong{border-color:#8ed8e8;color:#dffbff;background:#07151c}.encounterCue[data-kind="trial"]{background:rgba(18,12,3,.84)}.encounterCue[data-kind="trial"]>strong{border-color:#e6bd63;color:#fff0b7;background:#211607}.encounterCue[data-kind="boss"]{gap:10px;background:radial-gradient(circle at 50% 50%,rgba(70,32,65,.44),rgba(2,2,5,.94) 64%);animation:bossApproachIn 620ms steps(10,end) both}.encounterCue[data-kind="boss"]>span{border-color:#846c3e;color:#e8cb70}.encounterCue[data-kind="boss"]>strong{min-width:min(86vw,360px);padding:11px 14px;border:3px double #ffe784;color:#ffe784;background:#120b16;box-shadow:0 0 0 2px #030204,0 0 0 5px #533956,6px 7px #000;font-size:clamp(22px,7vw,32px);animation:bossTitlePulse 420ms steps(3,end) infinite}.encounterCue[data-kind="boss"]>b{color:#f5e8d0;font-size:12px}.encounterCue[data-kind="boss"]>i{width:220px;height:220px;border-color:rgba(255,231,132,.25);box-shadow:0 0 0 18px rgba(123,73,117,.08),0 0 0 36px rgba(255,231,132,.025)}
@keyframes dangerZoneIn{0%{opacity:0;transform:translate(-50%,-8px)}15%,72%{opacity:1;transform:translate(-50%,0)}100%{opacity:0;transform:translate(-50%,3px)}}@keyframes encounterShutterTop{0%{transform:translateY(-100%)}100%{transform:none}}@keyframes encounterShutterBottom{0%{transform:translateY(100%)}100%{transform:none}}@keyframes encounterCueOut{0%{opacity:0}100%{opacity:1}}@keyframes dangerEncounterPulse{0%{filter:brightness(1)}100%{filter:brightness(1.4)}}@keyframes bossApproachIn{0%{opacity:0;filter:brightness(2)}18%{opacity:1;filter:brightness(.6)}30%{filter:brightness(1.5)}45%,100%{filter:none}}@keyframes bossTitlePulse{0%,66%{filter:brightness(1)}67%,100%{filter:brightness(1.2)}}
@media(max-height:700px){.dangerWarning{top:max(80px,calc(env(safe-area-inset-top) + 70px));padding-block:4px}.encounterCue{gap:6px}.encounterCue>strong{padding:6px 11px;font-size:18px}.encounterCue[data-kind="boss"]>strong{padding:8px 10px;font-size:21px}}
@media(prefers-reduced-motion:reduce){.dangerWarning,.encounterCue,.encounterCue::before,.encounterCue::after,.encounterCue[data-kind="danger"]>strong,.encounterCue[data-kind="boss"],.encounterCue[data-kind="boss"]>strong{animation:none!important}}
'''
css.write_text(css.read_text() + addition)

section = '''\n\n## SFC Visual Reconstruction Pass 27 — Encounter warning & boss approach\n- Split pre-battle presentation into WILD ENCOUNTER, DANGER ENCOUNTER, fixed GUARDIAN, training TRIAL and BOSS APPROACH cues using the existing enemy/context data.\n- Added a short non-blocking warning when stepping from normal terrain into a danger tile so high-encounter regions announce themselves before the next fight.\n- Boss fixed encounters now use a distinct gold warning marker and a longer stepped approach shutter, while ordinary fixed enemies keep a shorter guardian cue.\n- Encounter meter math, encounter tables, fixed-enemy coordinates, boss flags, battle rules, rewards, save data and Chapter Battle remain unchanged.\n'''
progress.write_text(progress.read_text() + section)
