from pathlib import Path
p=Path('app/PrismOverdrive.tsx')
s=p.read_text()
s=s.replace('  const [routePulse, setRoutePulse] = useState(false);','  const [routePulse, setRoutePulse] = useState(false);\n  const [guideStep, setGuideStep] = useState(0);\n  const [showHelp, setShowHelp] = useState(false);\n  const [moves, setMoves] = useState(0);')
s=s.replace('    setBossBreaks(0); bossBreaksRef.current = 0;','    setBossBreaks(0); bossBreaksRef.current = 0;\n    setGuideStep(0); setShowHelp(false); setMoves(0);')
s=s.replace('    const group = connectedGroup(tiles, liveSeed);\n    const count = group.length;','    const group = connectedGroup(tiles, liveSeed);\n    const count = group.length;\n    setMoves((value) => value + 1);\n    if (guideStep < 2) setGuideStep((value) => value + 1);')
s=s.replace('  const cashValue = Math.round(comboBank * PHASE_META[runPhase].cash);','  const cashValue = Math.round(comboBank * PHASE_META[runPhase].cash);\n  const beginner = moves < 6;\n  const recommended = useMemo(() => {\n    if (routePlan?.ids?.length) return new Set(routePlan.ids);\n    const best = largestGroup(tiles);\n    return new Set(best.map((tile) => tile.id));\n  }, [tiles, routePlan]);\n  const guideTitle = moves === 0 ? "① SAME COLOR → TAP" : moves < 3 ? "② BIG GROUP = BIG SCORE" : routePlan ? "③ GLOWING ROUTE = GOOD MOVE" : "③ TARGET IS YOUR NEXT GOAL";\n  const guideText = moves === 0 ? "同じ色がつながった場所をタップ。まずはそれだけでOK。" : moves < 3 ? "つながりが大きいほど高得点。光っている候補を狙おう。" : routePlan ? "ROUTE表示を消すと、予告パネルがつながって連鎖しやすい。" : "上のTARGETを狙う。細かいゲージは慣れてからでOK。";')
s=s.replace('''      <div className={styles.introRules}>\n        <b>BUILD → AIM → RELEASE → CASH OUT</b>\n        <span>SMALL BREAK = CHARGE</span><span>BIG BREAK = RELEASE</span>\n        <span>TARGET ×3 = BOSS CORE</span><span>SCAN ROUTE = PLANNED CHAIN</span>\n      </div>''','''      <div className={styles.introRules}>\n        <b>遊び方は1つだけ</b>\n        <strong>同じ色がつながった場所をタップ</strong>\n        <span>大きくつなげて消すほど高得点！</span>\n        <span>最初のプレイ中に順番に教えます</span>\n      </div>''')
s=s.replace('''    <section className={styles.strategyPanel} data-target-pulse={targetPulse ? "true" : "false"} aria-label="Overdrive strategy panel">''','''    <section className={styles.guideBar} data-done={beginner ? "false" : "true"}>\n      <div><strong>{guideTitle}</strong><span>{guideText}</span></div>\n      <button type="button" onClick={() => setShowHelp(true)}>？</button>\n    </section>\n\n    <section className={`${styles.strategyPanel} ${beginner ? styles.strategyBeginner : ""}`} data-target-pulse={targetPulse ? "true" : "false"} aria-label="Overdrive strategy panel">''')
s=s.replace('''      <div className={styles.phaseCard} data-phase={runPhase}><span>PHASE</span><strong>{PHASE_META[runPhase].label}</strong><em>{PHASE_META[runPhase].note}</em></div>''','''      {!beginner ? <div className={styles.phaseCard} data-phase={runPhase}><span>PHASE</span><strong>{PHASE_META[runPhase].label}</strong><em>{PHASE_META[runPhase].note}</em></div> : null}''')
s=s.replace('''      <div className={styles.scanCard} data-route={routePlan ? "ready" : "none"}>''','''      {!beginner ? <div className={styles.scanCard} data-route={routePlan ? "ready" : "none"}>''')
s=s.replace('''</strong><em>{routePlan ? `ROUTE READY → ${LABEL[routePlan.type]} ×${routePlan.projected}` : "NO ROUTE • SHAPE THE COLUMN"}</em></div>\n      <button className={styles.cashOut}''','''</strong><em>{routePlan ? `ROUTE READY → ${LABEL[routePlan.type]} ×${routePlan.projected}` : "NO ROUTE • SHAPE THE COLUMN"}</em></div> : null}\n      {!beginner ? <button className={styles.cashOut}''')
s=s.replace('''</strong><em>{comboBank > 0 ? "SECURE • RESET COMBO + STREAK" : "BUILD BANK WITH COMBO"}</em></button>\n      <div className={styles.missionCard}''','''</strong><em>{comboBank > 0 ? "得点を確定 / COMBO終了" : "COMBOでBANKがたまる"}</em></button> : null}\n      {!beginner ? <div className={styles.missionCard}''')
s=s.replace('''</strong><em>{bossCoreHp > 0 ? "RELEASE • ROUTE • CHAIN 2+" : "3 TARGETS WITHOUT COMBO BREAK"}</em><u><i style={{ width: `${bossCoreHp > 0 ? bossCoreHp / Math.max(1, bossCoreMax) * 100 : missionStreak / 3 * 100}%` }} /></u></div>\n      <div className={styles.chargeRow}''','''</strong><em>{bossCoreHp > 0 ? "CHARGE / ROUTE / CHAINで攻撃" : "TARGETを3回連続達成"}</em><u><i style={{ width: `${bossCoreHp > 0 ? bossCoreHp / Math.max(1, bossCoreMax) * 100 : missionStreak / 3 * 100}%` }} /></u></div> : null}\n      {!beginner ? <div className={styles.chargeRow}''')
s=s.replace('''</u></span>)}</div>\n    </section>''','''</u></span>)}</div> : null}\n    </section>''',1)
old='''${routeIds.has(tile.id) ? styles.routeReady : ""}`}'''
new='''${routeIds.has(tile.id) ? styles.routeReady : ""} ${beginner && recommended.has(tile.id) ? styles.recommended : ""}`}'''
s=s.replace(old,new)
s=s.replace('''    {modeFx ? <div key={modeFx.token}''','''    {showHelp ? <div className={styles.helpOverlay} role="dialog" aria-label="Prism Overdrive help"><div><button type="button" onClick={() => setShowHelp(false)}>×</button><h2>遊び方</h2><p><b>1.</b> 同じ色がつながった場所をタップ</p><p><b>2.</b> 大きな塊ほど高得点</p><p><b>3.</b> TARGETを狙うとボーナス</p><p><b>4.</b> ROUTEが光ったら狙い目</p><p><b>5.</b> CASH OUTでBANK得点を安全に確定</p><small>CHARGEやBOSS COREはプレイしているうちに自然に使えます。最初から覚える必要はありません。</small></div></div> : null}\n\n    {modeFx ? <div key={modeFx.token}''')
p.write_text(s)

p=Path('app/PrismOverdrive.module.css')
c=p.read_text()+'''\n\n/* PASS 49 — ONBOARDING / READABILITY */\n.introRules{grid-template-columns:1fr!important}.introRules strong{display:block;padding:8px 5px;border:2px solid #65f5ff;background:#07151d;color:#fff36d;font-size:12px}.introRules b{font-size:9px}.introRules span{font-size:7px}\n.guideBar{min-height:43px;margin:0 0 4px;padding:4px 5px;border:2px solid #66f2ff;background:#06131d;display:grid;grid-template-columns:1fr 34px;align-items:center;gap:5px;box-shadow:inset 0 0 0 1px #15384b}.guideBar>div{display:grid;gap:2px}.guideBar strong{font-size:9px;color:#fff36d}.guideBar span{font-size:6px;color:#d8efff;line-height:1.25}.guideBar button{appearance:none;width:32px;height:32px;border:2px solid #fff36d;background:#141027;color:#fff36d;font:1000 16px/1 monospace;touch-action:manipulation}.guideBar[data-done="true"]{min-height:35px;border-color:#344b61;background:#040a11}.guideBar[data-done="true"] strong{font-size:7px}.guideBar[data-done="true"] span{font-size:5px}\n.strategyBeginner{grid-template-columns:1fr!important;min-height:42px!important}.strategyBeginner .targetCard{min-height:36px;display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:6px}.strategyBeginner .targetCard span{font-size:6px}.strategyBeginner .targetCard strong{font-size:10px;text-align:center}.strategyBeginner .targetCard em{font-size:6px;color:#fff36d}\n.recommended{z-index:4!important;animation:recommendedPulse 760ms steps(4,end) infinite!important;box-shadow:inset 0 0 0 3px #fff,inset 0 0 0 5px var(--edge),0 0 15px #fff36d!important}.recommended::after{content:"TAP"!important;position:absolute;right:2px;top:2px;padding:2px;background:#fff36d;color:#07090e;font:1000 5px/1 monospace;opacity:1!important;z-index:7}@keyframes recommendedPulse{50%{filter:brightness(1.55);transform:scale(.96)}}\n.helpOverlay{position:absolute;z-index:80;inset:0;display:grid;place-items:center;padding:16px;background:rgba(1,3,8,.88)}.helpOverlay>div{position:relative;width:min(94%,370px);padding:15px;border:3px solid #65f5ff;background:#07101a;box-shadow:0 0 0 3px #241044,7px 8px #000}.helpOverlay h2{margin:0 0 10px;color:#fff36d;font-size:18px}.helpOverlay p{margin:6px 0;padding:6px;border:1px solid #294057;background:#040911;color:#e7f5ff;font-size:9px;line-height:1.35}.helpOverlay p b{color:#65f5ff}.helpOverlay small{display:block;margin-top:9px;color:#91a9bf;font-size:7px;line-height:1.5}.helpOverlay button{position:absolute;right:7px;top:7px;width:32px;height:32px;border:2px solid #73849a;background:#080b12;color:#fff;font:1000 18px/1 monospace}\n@media(max-height:700px){.guideBar{min-height:35px}.guideBar strong{font-size:7px}.guideBar span{font-size:5px}.guideBar button{width:28px;height:28px}.strategyBeginner{min-height:34px!important}.strategyBeginner .targetCard{min-height:29px}.strategyBeginner .targetCard strong{font-size:8px}}\n@media(prefers-reduced-motion:reduce){.recommended{animation:none!important}}\n'''
p.write_text(c)
# trigger: onboarding-browser-qa-20260830
